version: "3.8"
services:

  webui:
    image: ghcr.io/open-webui/open-webui:main
    expose:
     - 8080/tcp
    ports:
     - 8085:8080/tcp
    environment:
     - OLLAMA_BASE_URL=http://ollama:11434
     # uncomment the following if you are running ollama on the docker host and remove the ollama service below
     #- OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui:/app/backend/data
    depends_on:
     - ollama

  ollama:
    image: ollama/ollama
    expose:
     - 11434/tcp
    ports:
     - 11434:11434/tcp
    healthcheck:
      test: ollama --version || exit 1
    command: serve
    volumes:
      - ollama:/root/.ollama
    devices:
      - /dev/dri:/dev/dri


volumes:
  ollama:
  open-webui:

networks:
  default:
    external:
      name: nginx-proxy